(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))f(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&f(u)}).observe(document,{childList:!0,subtree:!0});function c(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function f(r){if(r.ep)return;r.ep=!0;const s=c(r);fetch(r.href,s)}})();const o={todoInput:document.querySelector(".todo-input"),todoCounter:document.querySelector(".todo-counter"),clearCompletedBtn:document.querySelector(".todo-list-button"),filtersList:document.querySelector(".filters-list"),creationWrapper:document.querySelector(".creation-wrapper"),filtersWrapper:document.querySelector(".filters-wrapper"),todoWrapper:document.querySelector(".todo-wrapper"),todoList:document.querySelector(".todo-list"),themeBtn:document.querySelector(".theme-button"),themeIcon:document.querySelector("#theme-icon"),backgroundImg:document.querySelector("#bg-img")},d={TODO:"todos",THEME_KEY:"theme"};let n=JSON.parse(localStorage.getItem(d.TODO))||[],p="all",l=localStorage.getItem(d.THEME_KEY)||"light";function a(){localStorage.setItem(d.TODO,JSON.stringify(n))}function g(){const t=n.filter(e=>!e.completed).length;o.todoCounter.textContent=t}function h(){return p==="active"?n.filter(t=>!t.completed):p==="completed"?n.filter(t=>t.completed):n}function i(){o.todoList.innerHTML="",h().forEach(e=>{const c=document.createElement("li");c.classList.add("todo-item"),c.dataset.id=e.id,c.innerHTML=`
      <label class="todo-label">
        <input class="todo-checkbox" type="checkbox" ${e.completed?"checked":""} />
        <span class="custom-checkbox"></span>
      </label>

      <p class="todo-text ${e.completed?"completed":""}">
        ${e.text}
      </p>

      <button class="todo-delete-btn" type="button"></button>
    `,o.todoList.appendChild(c)}),g()}function m(t){const e={id:Date.now(),text:t,completed:!1};n.unshift(e),a(),i()}function L(t){n=n.filter(e=>e.id!==t),a(),i()}function y(t){n=n.map(e=>e.id===t?{...e,completed:!e.completed}:e),a(),i()}function b(){n=n.filter(t=>!t.completed),a(),i()}function v(t){o.filtersList.querySelectorAll(".filters-button").forEach(c=>c.classList.remove("active")),t.classList.add("active")}function E(){l==="light"?(document.body.classList.add("light"),o.filtersWrapper.classList.add("light"),o.todoWrapper.classList.add("light"),o.creationWrapper.classList.add("light"),o.themeIcon.src="/assets/icon-moon.svg",o.themeIcon.alt="Moon icon"):(document.body.classList.remove("light"),o.filtersWrapper.classList.remove("light"),o.todoWrapper.classList.remove("light"),o.creationWrapper.classList.remove("light"),o.themeIcon.src="/assets/icon-sun.svg",o.themeIcon.alt="Sun icon")}o.themeBtn.addEventListener("click",()=>{l=l==="light"?"dark":"light",localStorage.setItem(d.THEME_KEY,l),E()});o.todoInput.addEventListener("keydown",t=>{if(t.key!=="Enter")return;const e=o.todoInput.value.trim();e&&(m(e),o.todoInput.value="")});o.creationWrapper.addEventListener("click",t=>{if(!t.target.classList.contains("todo-checkbox"))return;const e=o.todoInput.value.trim();if(!e){t.target.checked=!1;return}m(e),o.todoInput.value="",t.target.checked=!1});o.todoList.addEventListener("click",t=>{const e=t.target.closest(".todo-item");if(!e)return;const c=Number(e.dataset.id);if(t.target.classList.contains("todo-delete-btn")){L(c);return}t.target.classList.contains("todo-checkbox")&&y(c)});o.clearCompletedBtn.addEventListener("click",b);o.filtersList.addEventListener("click",t=>{if(!t.target.classList.contains("filters-button"))return;p=t.target.textContent.toLowerCase(),v(t.target),i()});i();
//# sourceMappingURL=index.js.map
